In [1]:
import torch

# Torch Tensors

In [2]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
print(b.view(-1,1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


In [15]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred (4x3) (12x1)
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-0.6448, -0.7070,  0.2448, -0.1845],
         [ 0.6283,  0.3691, -1.1658, -0.5500],
         [ 0.8514, -0.4000,  0.3119, -0.9622]],

        [[ 0.2266,  1.0353,  0.5515,  0.7985],
         [-0.3727, -0.5898, -1.7562, -0.7155],
         [ 1.0802, -0.6098,  0.0704, -0.5965]]])
tensor([[-0.6448, -0.7070,  0.2448, -0.1845,  0.6283,  0.3691, -1.1658, -0.5500,
          0.8514, -0.4000,  0.3119, -0.9622],
        [ 0.2266,  1.0353,  0.5515,  0.7985, -0.3727, -0.5898, -1.7562, -0.7155,
          1.0802, -0.6098,  0.0704, -0.5965]])
tensor([[-0.6448, -0.7070,  0.2448, -0.1845,  0.6283

In [16]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.1520, 0.0879, 0.5473, 0.8216],
        [0.9149, 0.6955, 0.8931, 0.4460],
        [0.3416, 0.1554, 0.0483, 0.1534],
        [0.5473, 0.3197, 0.0861, 0.6598]])


In [17]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.0372, -1.0965, -0.3743, -0.4851],
        [ 1.6373,  1.7240, -3.1758,  1.0520],
        [-0.6969, -0.3877, -0.1002, -1.0641],
        [-1.9048,  0.2388,  0.3510,  0.9365]])
torch.float32


In [18]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([9, 6, 6, 7, 8])
torch.int64


In [19]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[7, 9, 6],
        [6, 7, 6],
        [9, 8, 7]])


In [20]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [21]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [22]:
#r2 = torch.randn(4,4)
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[ 0.7893, -1.6368,  2.6852,  0.5307],
        [ 1.1147,  0.6232,  1.8796,  1.2018],
        [-0.1070,  0.7851, -1.2290,  1.0277],
        [ 0.8981, -0.1853,  0.0398, -1.0570]], dtype=torch.float64)


In [23]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 0.1148, -1.0086,  0.1731,  0.3365],
        [ 2.5522,  2.4195, -2.2827,  1.4981],
        [-0.3553, -0.2323, -0.0519, -0.9107],
        [-1.3575,  0.5585,  0.4371,  1.5963]])


In [24]:
#In-place addition (change the value of r2)
r2.add_(r)    #r2 = torch.add(r,r2) r2 = r + r2
print(r2)

tensor([[ 0.1148, -1.0086,  0.1731,  0.3365],
        [ 2.5522,  2.4195, -2.2827,  1.4981],
        [-0.3553, -0.2323, -0.0519, -0.9107],
        [-1.3575,  0.5585,  0.4371,  1.5963]])


In [25]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-3.1538, -0.9474, -0.1537, -1.0624],
        [-1.2590, -0.1644,  0.2341,  0.0393],
        [-0.0746, -0.9727, -0.9996, -0.0628],
        [ 0.1206,  1.2393, -0.5536, -0.0149]])
torch.float32


In [26]:
#Matrix Slicing Operation

print(r2[:,1])  #All the rows in the first column
print(r2[:,:2]) #All the rows from column 0 to up until 2 (excluding 2)
print(r2[:3,:]) #All the rows until 2 and all the columns
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item()) #extract the number from tensor
print(r2[2,:])

tensor([-0.9474, -0.1644, -0.9727,  1.2393])
tensor([[-3.1538, -0.9474],
        [-1.2590, -0.1644],
        [-0.0746, -0.9727],
        [ 0.1206,  1.2393]])
tensor([[-3.1538, -0.9474, -0.1537, -1.0624],
        [-1.2590, -0.1644,  0.2341,  0.0393],
        [-0.0746, -0.9727, -0.9996, -0.0628]])
tensor(-0.0628)
-0.06284154951572418
tensor([-0.0746, -0.9727, -0.9996, -0.0628])


## Numpy Bridge

In [27]:
import numpy as np

In [28]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b) #numpy array afftected by the torch tensor and this is called numpy bridge
#whatever happens on pytorch tensor also happens on numpy array

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [29]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a) #this is how we do inplace operation in numpy array
print(a)
print(b)
#again we see that they are affected by each other

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [30]:
#Move the tensor to the GPU
#To speed up the computation
#r2 = torch.randn(4,4)
r2 = r2.cuda()
print(r2)

tensor([[-3.1538, -0.9474, -0.1537, -1.0624],
        [-1.2590, -0.1644,  0.2341,  0.0393],
        [-0.0746, -0.9727, -0.9996, -0.0628],
        [ 0.1206,  1.2393, -0.5536, -0.0149]], device='cuda:0')


In [31]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
add_result = torch.ones(5)
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [32]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [33]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [34]:
#Tensor Concatenation
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1]) #They are just concatenated along the rows
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[-0.1593, -0.5412,  1.9941, -0.1635,  0.3915],
        [ 1.8772,  0.1240, -1.0693,  0.5378,  0.0754]])
tensor([[ 0.9732,  0.7348, -0.8170, -0.5190,  0.7311],
        [-1.6219,  0.0606,  0.0193, -1.7091,  0.4067],
        [ 0.5329, -0.3023, -2.8233,  1.2926,  1.2651]])


tensor([[-0.1593, -0.5412,  1.9941, -0.1635,  0.3915],
        [ 1.8772,  0.1240, -1.0693,  0.5378,  0.0754],
        [ 0.9732,  0.7348, -0.8170, -0.5190,  0.7311],
        [-1.6219,  0.0606,  0.0193, -1.7091,  0.4067],
        [ 0.5329, -0.3023, -2.8233,  1.2926,  1.2651]])


tensor([[-0.1568, -0.8716,  0.8139],
        [-1.1996,  0.4861, -0.5074]])
tensor([[-1.0284,  1.4343,  0.0379,  0.9249, -2.8766],
        [-1.0872, -1.3713, -0.8981, -0.9317, -0.7392]])


tensor([[-0.1568, -0.8716,  0.8139, -1.0284,  1.4343,  0.0379,  0.9249, -2.8766],
        [-1.1996,  0.4861, -0.5074, -1.0872, -1.3713, -0.8981, -0.9317, -0.7392]])




## Adding Dimensions to Tensors

In [35]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4]) #4
tensor_a = torch.unsqueeze(tensor_1, 0) #1x4
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1) #4x1
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.1539, 0.1306, 0.6058, 0.2339],
         [0.5561, 0.6363, 0.2523, 0.3853],
         [0.8599, 0.5682, 0.6133, 0.3886]],

        [[0.5895, 0.7332, 0.3863, 0.0800],
         [0.9303, 0.4661, 0.8792, 0.6195],
         [0.9767, 0.0274, 0.8958, 0.5765]]])


tensor([[0.6058, 0.2523, 0.6133],
        [0.3863, 0.8792, 0.8958]])
torch.Size([2, 3])


tensor([[[0.6058],
         [0.2523],
         [0.6133]],

        [[0.3863],
         [0.8792],
         [0.8958]]])
torch.Size([2, 3, 1])


## AutoGrad

In [36]:
#If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we can compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [37]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward() #compute all the derivatives at once
print(x.grad) #derivative of s with respect to x

tensor([1., 1., 1.])


In [38]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y #z does not know who created it
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_() #do an inplace operation
y.requires_grad_() #do an inplace operation
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten.
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [40]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
